// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// モデルの状態を表す4値(design.md §2.2、requirements.md FR-1)。
///
/// `pigeons/offline_stt_events.dart` の同名enumと値・順序を一致させる
/// こと(重複定義の理由は本ファイル冒頭コメント参照)。
enum ModelState {
  available,
  downloadable,
  downloading,
  unavailable,
}

/// 共通エラー型(requirements.md FR-6、design.md §2.2 の `TranscribeException`
/// sealed階層に対応する列挙型)。
///
/// C++/WinRTはPigeonのsealed class生成対象外である
/// (Kotlin/Swift/C++いずれの生成器も `_errorOnSealedClass` により拒否する)
/// ため、型安全にエラー種別を伝える手段としてこの列挙型を用いる。
/// Windows実装では特に、後述の `OfflineSttStreamCallbackApi.onStreamError`
/// のワイヤ型としてそのまま使用する(EventChannelの組み込みエラーシンクが
/// 無いため、明示的なコールバックとして表現する必要がある)。
///
/// `PlatformException_`(design.mdの命名)には `code` / `message` の
/// 自由形式フィールドがあるため、`platformError` 1値に対応させる。
enum TranscribeErrorCode {
  modelUnavailable,
  localeUnsupported,
  decodeFailed,
  deviceUnsupported,
  cancelled,
  platformError,
}

/// モデルダウンロードの進捗(design.md §2.2)。
///
/// design.md §4.4 のとおり、Windowsは `EnsureReadyAsync()` の進捗API粒度が
/// 粗い場合があり、`fraction: null` の不定進捗として通知することを想定する。
class DownloadProgress {
  DownloadProgress({
    this.fraction,
    required this.completed,
  });

  /// 進捗率(0.0〜1.0)。`null` は不定進捗を表す。
  double? fraction;

  /// ダウンロードが完了したかどうか。
  bool completed;

  List<Object?> _toList() {
    return <Object?>[
      fraction,
      completed,
    ];
  }

  Object encode() {
    return _toList();  }

  static DownloadProgress decode(Object result) {
    result as List<Object?>;
    return DownloadProgress(
      fraction: result[0] as double?,
      completed: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fraction, other.fraction) && _deepEquals(completed, other.completed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DownloadProgress(fraction: $fraction, completed: $completed)';
  }
}

/// `transcribeFile` へ渡すリクエスト(design.md §2.2)。
///
/// 注記: 現行の design.md §2.2 に `playbackRate` フィールドは存在しない
/// (2026-09-20 時点。PR #74 で追加予定だが本ブランチは分岐前のため未反映)。
/// そのため本スキーマでも `path` / `locale` の2フィールドのみを定義する。
class TranscribeRequest {
  TranscribeRequest({
    required this.path,
    required this.locale,
  });

  /// 文字起こし対象の音声ファイルパス。
  String path;

  /// BCP-47形式のロケール(例: `ja-JP`)。
  String locale;

  List<Object?> _toList() {
    return <Object?>[
      path,
      locale,
    ];
  }

  Object encode() {
    return _toList();  }

  static TranscribeRequest decode(Object result) {
    result as List<Object?>;
    return TranscribeRequest(
      path: result[0]! as String,
      locale: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TranscribeRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(locale, other.locale);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TranscribeRequest(path: $path, locale: $locale)';
  }
}

/// 文字起こし結果の1セグメント(design.md §2.2)。
///
/// design.md §4.4 のとおり、Windowsのバッチ認識は `isFinal: true` のセグ
/// メントを1回だけemitする想定である。
class TranscriptSegment {
  TranscriptSegment({
    required this.text,
    required this.isFinal,
  });

  /// 認識されたテキスト。
  String text;

  /// 確定結果かどうか(`false` はpartial)。
  bool isFinal;

  List<Object?> _toList() {
    return <Object?>[
      text,
      isFinal,
    ];
  }

  Object encode() {
    return _toList();  }

  static TranscriptSegment decode(Object result) {
    result as List<Object?>;
    return TranscriptSegment(
      text: result[0]! as String,
      isFinal: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TranscriptSegment || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) && _deepEquals(isFinal, other.isFinal);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TranscriptSegment(text: $text, isFinal: $isFinal)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ModelState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is TranscribeErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DownloadProgress) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TranscribeRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is TranscriptSegment) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ModelState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : TranscribeErrorCode.values[value];
      case 131:
        return DownloadProgress.decode(readValue(buffer)!);
      case 132:
        return TranscribeRequest.decode(readValue(buffer)!);
      case 133:
        return TranscriptSegment.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Method チャネル(design.md §2.3)。
///
/// `downloadModel` / `transcribeFile` は開始のみを担う。進捗・結果は
/// 下記 `OfflineSttStreamCallbackApi`(FlutterApiコールバック)で配信する。
class OfflineSttHostApi {
  /// Constructor for [OfflineSttHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OfflineSttHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 対象ロケールのモデル状態を確認する(requirements.md FR-1)。
  ///
  /// ## `@async` を付与する理由
  /// `pigeons/offline_stt_events.dart` の同名メソッドと契約(HostApi)を
  /// 揃えるため付与する。design.md §4.4 のとおりWindowsの写像元は
  /// `GetReadyState()`(Async接尾辞が無いためAPI自体は同期の見込み)だが、
  /// PigeonのC++生成器は `@async` を付けたメソッドを
  /// `std::function<void(ErrorOr<ModelState> reply)>` を受け取るコール
  /// バック形式で生成する(実際に生成して確認済み。`windows/pigeon.g.h`
  /// 参照)。M4実装では `GetReadyState()` の結果を即座に
  /// `result(...)` で返せばよく、同期実装しか用意できない場合でも
  /// 不利にならない。将来的にWindows側の判定処理が非同期化しても
  /// このコールバック形式のまま自然に対応できる。
  Future<ModelState> checkModel(String locale) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_windows.OfflineSttHostApi.checkModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ModelState;
  }

  /// モデルダウンロードを開始する(requirements.md FR-2)。
  ///
  /// 進捗は `OfflineSttStreamCallbackApi.onDownloadProgress` で配信される。
  /// 本メソッド自体は開始要求のみを表し、値を返さない。
  ///
  /// ## `@async` を付けない理由
  /// `pigeons/offline_stt_events.dart` の同名メソッドと同様「開始要求
  /// のみ」の契約である。`EnsureReadyAsync()`(design.md §4.4)の完了を
  /// 待たずに開始要求だけを受け付けて直ちに制御を返せる設計とし、進捗・
  /// 完了は `OfflineSttStreamCallbackApi.onDownloadProgress` /
  /// `onStreamDone` で別途通知する。
  Future<void> downloadModel(String locale) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_windows.OfflineSttHostApi.downloadModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 音声ファイルの文字起こしを開始する(requirements.md FR-3)。
  ///
  /// 結果は `OfflineSttStreamCallbackApi.onSegment` で配信される。
  /// 本メソッド自体は開始要求のみを表し、値を返さない。
  ///
  /// design.md §3 のとおり、`checkModel()` が `ModelState.available` 以外
  /// を返す状態でこのメソッドが呼ばれた場合、ネイティブ側は即座にエラーを
  /// 返さなければならない(内部で暗黙的にダウンロードを開始してはならない)。
  ///
  /// ## `@async` を付けない理由
  /// `downloadModel` と同様に「開始要求のみ」の契約であり、
  /// `BatchRecognition.RecognizeFromFile` の完了を待たずに開始要求だけを
  /// 受け付けて直ちに制御を返せる。
  Future<void> transcribeFile(TranscribeRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_windows.OfflineSttHostApi.transcribeFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 実行中のダウンロード、または文字起こしセッションをキャンセルする
  /// (requirements.md FR-3)。
  ///
  /// design.md §3 のとおり同時セッションはv1では1本に制限されるため、
  /// キャンセル対象を明示するパラメータは持たない(実行中の1本のみが
  /// 対象になる)。
  ///
  /// ## `@async` を付けない理由
  /// 実行中の非同期処理へキャンセル要求を送るだけの同期的な操作である
  /// (完了を待つ必要がない)。
  Future<void> cancel() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_windows.OfflineSttHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// FlutterApiコールバック(design.md §2.3)。Windows(C++/WinRT) 向け。
///
/// Android/Darwinの `@EventChannelApi` に相当するストリーム機能を、Pigeon
/// の C++ 生成器が対応していないため `@FlutterApi()` のコールバック列で
/// 代替する(本ファイル冒頭のコメント参照)。EventChannelと異なり暗黙の
/// ストリーム終了・エラー伝播が無いため、`onStreamError` /
/// `onStreamDone` を明示的なメソッドとして定義する。
abstract class OfflineSttStreamCallbackApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// 文字起こし結果1件を通知する(requirements.md FR-3)。
  ///
  /// design.md §4.4 のとおりWindowsは `isFinal: true` の1件のみをemitし、
  /// 直後に `onStreamDone` が呼ばれる想定である。
  void onSegment(TranscriptSegment segment);

  /// モデルダウンロード進捗を通知する(requirements.md FR-2)。
  void onDownloadProgress(DownloadProgress progress);

  /// ストリームがエラーで終了したことを通知する(requirements.md FR-6)。
  ///
  /// `message` はプラットフォーム固有の詳細情報(存在する場合)であり、
  /// `code` が `TranscribeErrorCode.platformError` の場合に主として使う
  /// 想定である。
  void onStreamError(TranscribeErrorCode code, String? message);

  /// ストリームが正常に終了したことを通知する。
  void onStreamDone();

  static void setUp(OfflineSttStreamCallbackApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.offline_stt_windows.OfflineSttStreamCallbackApi.onSegment$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final TranscriptSegment arg_segment = args[0]! as TranscriptSegment;
          try {
            api.onSegment(arg_segment);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.offline_stt_windows.OfflineSttStreamCallbackApi.onDownloadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final DownloadProgress arg_progress = args[0]! as DownloadProgress;
          try {
            api.onDownloadProgress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.offline_stt_windows.OfflineSttStreamCallbackApi.onStreamError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final TranscribeErrorCode arg_code = args[0]! as TranscribeErrorCode;
          final String? arg_message = args[1] as String?;
          try {
            api.onStreamError(arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.offline_stt_windows.OfflineSttStreamCallbackApi.onStreamDone$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onStreamDone();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
