// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PIGEON_G_H_
#define PIGEON_PIGEON_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace offline_stt_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class OfflineSttHostApi;
  friend class OfflineSttStreamCallbackApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// モデルの状態を表す4値(design.md §2.2、requirements.md FR-1)。
//
// `pigeons/offline_stt_events.dart` の同名enumと値・順序を一致させる
// こと(重複定義の理由は本ファイル冒頭コメント参照)。
enum class ModelState {
  kAvailable = 0,
  kDownloadable = 1,
  kDownloading = 2,
  kUnavailable = 3
};

// 共通エラー型(requirements.md FR-6、design.md §2.2 の `TranscribeException`
// sealed階層に対応する列挙型)。
//
// C++/WinRTはPigeonのsealed class生成対象外である
// (Kotlin/Swift/C++いずれの生成器も `_errorOnSealedClass` により拒否する)
// ため、型安全にエラー種別を伝える手段としてこの列挙型を用いる。
// Windows実装では特に、後述の `OfflineSttStreamCallbackApi.onStreamError`
// のワイヤ型としてそのまま使用する(EventChannelの組み込みエラーシンクが
// 無いため、明示的なコールバックとして表現する必要がある)。
//
// `PlatformException_`(design.mdの命名)には `code` / `message` の
// 自由形式フィールドがあるため、`platformError` 1値に対応させる。
enum class TranscribeErrorCode {
  kModelUnavailable = 0,
  kLocaleUnsupported = 1,
  kDecodeFailed = 2,
  kDeviceUnsupported = 3,
  kCancelled = 4,
  kPlatformError = 5
};


// モデルダウンロードの進捗(design.md §2.2)。
//
// design.md §4.4 のとおり、Windowsは `EnsureReadyAsync()` の進捗API粒度が
// 粗い場合があり、`fraction: null` の不定進捗として通知することを想定する。
//
// Generated class from Pigeon that represents data sent in messages.
class DownloadProgress {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DownloadProgress(bool completed);

  // Constructs an object setting all fields.
  explicit DownloadProgress(
    const double* fraction,
    bool completed);

  // 進捗率(0.0〜1.0)。`null` は不定進捗を表す。
  const double* fraction() const;
  void set_fraction(const double* value_arg);
  void set_fraction(double value_arg);

  // ダウンロードが完了したかどうか。
  bool completed() const;
  void set_completed(bool value_arg);

  bool operator==(const DownloadProgress& other) const;
  bool operator!=(const DownloadProgress& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const DownloadProgress& obj);
 private:
  static DownloadProgress FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class OfflineSttHostApi;
  friend class OfflineSttStreamCallbackApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<double> fraction_;
  bool completed_;
};


// `transcribeFile` へ渡すリクエスト(design.md §2.2)。
//
// 注記: 現行の design.md §2.2 に `playbackRate` フィールドは存在しない
// (2026-09-20 時点。PR #74 で追加予定だが本ブランチは分岐前のため未反映)。
// そのため本スキーマでも `path` / `locale` の2フィールドのみを定義する。
//
// Generated class from Pigeon that represents data sent in messages.
class TranscribeRequest {
 public:
  // Constructs an object setting all fields.
  explicit TranscribeRequest(
    const std::string& path,
    const std::string& locale);

  // 文字起こし対象の音声ファイルパス。
  const std::string& path() const;
  void set_path(std::string_view value_arg);

  // BCP-47形式のロケール(例: `ja-JP`)。
  const std::string& locale() const;
  void set_locale(std::string_view value_arg);

  bool operator==(const TranscribeRequest& other) const;
  bool operator!=(const TranscribeRequest& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const TranscribeRequest& obj);
 private:
  static TranscribeRequest FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class OfflineSttHostApi;
  friend class OfflineSttStreamCallbackApi;
  friend class PigeonInternalCodecSerializer;
  std::string path_;
  std::string locale_;
};


// 文字起こし結果の1セグメント(design.md §2.2)。
//
// design.md §4.4 のとおり、Windowsのバッチ認識は `isFinal: true` のセグ
// メントを1回だけemitする想定である。
//
// Generated class from Pigeon that represents data sent in messages.
class TranscriptSegment {
 public:
  // Constructs an object setting all fields.
  explicit TranscriptSegment(
    const std::string& text,
    bool is_final);

  // 認識されたテキスト。
  const std::string& text() const;
  void set_text(std::string_view value_arg);

  // 確定結果かどうか(`false` はpartial)。
  bool is_final() const;
  void set_is_final(bool value_arg);

  bool operator==(const TranscriptSegment& other) const;
  bool operator!=(const TranscriptSegment& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const TranscriptSegment& obj);
 private:
  static TranscriptSegment FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class OfflineSttHostApi;
  friend class OfflineSttStreamCallbackApi;
  friend class PigeonInternalCodecSerializer;
  std::string text_;
  bool is_final_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Method チャネル(design.md §2.3)。
//
// `downloadModel` / `transcribeFile` は開始のみを担う。進捗・結果は
// 下記 `OfflineSttStreamCallbackApi`(FlutterApiコールバック)で配信する。
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class OfflineSttHostApi {
 public:
  OfflineSttHostApi(const OfflineSttHostApi&) = delete;
  OfflineSttHostApi& operator=(const OfflineSttHostApi&) = delete;
  virtual ~OfflineSttHostApi() {}
  // 対象ロケールのモデル状態を確認する(requirements.md FR-1)。
  virtual ErrorOr<ModelState> CheckModel(const std::string& locale) = 0;
  // モデルダウンロードを開始する(requirements.md FR-2)。
  //
  // 進捗は `OfflineSttStreamCallbackApi.onDownloadProgress` で配信される。
  // 本メソッド自体は開始要求のみを表し、値を返さない。
  virtual std::optional<FlutterError> DownloadModel(const std::string& locale) = 0;
  // 音声ファイルの文字起こしを開始する(requirements.md FR-3)。
  //
  // 結果は `OfflineSttStreamCallbackApi.onSegment` で配信される。
  // 本メソッド自体は開始要求のみを表し、値を返さない。
  //
  // design.md §3 のとおり、`checkModel()` が `ModelState.available` 以外
  // を返す状態でこのメソッドが呼ばれた場合、ネイティブ側は即座にエラーを
  // 返さなければならない(内部で暗黙的にダウンロードを開始してはならない)。
  virtual std::optional<FlutterError> TranscribeFile(const TranscribeRequest& request) = 0;
  // 実行中のダウンロード、または文字起こしセッションをキャンセルする
  // (requirements.md FR-3)。
  //
  // design.md §3 のとおり同時セッションはv1では1本に制限されるため、
  // キャンセル対象を明示するパラメータは持たない(実行中の1本のみが
  // 対象になる)。
  virtual std::optional<FlutterError> Cancel() = 0;

  // The codec used by OfflineSttHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `OfflineSttHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    OfflineSttHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    OfflineSttHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  OfflineSttHostApi() = default;
};
// FlutterApiコールバック(design.md §2.3)。Windows(C++/WinRT) 向け。
//
// Android/Darwinの `@EventChannelApi` に相当するストリーム機能を、Pigeon
// の C++ 生成器が対応していないため `@FlutterApi()` のコールバック列で
// 代替する(本ファイル冒頭のコメント参照)。EventChannelと異なり暗黙の
// ストリーム終了・エラー伝播が無いため、`onStreamError` /
// `onStreamDone` を明示的なメソッドとして定義する。
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class OfflineSttStreamCallbackApi {
 public:
  OfflineSttStreamCallbackApi(::flutter::BinaryMessenger* binary_messenger);
  OfflineSttStreamCallbackApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  // 文字起こし結果1件を通知する(requirements.md FR-3)。
  //
  // design.md §4.4 のとおりWindowsは `isFinal: true` の1件のみをemitし、
  // 直後に `onStreamDone` が呼ばれる想定である。
  void OnSegment(
    const TranscriptSegment& segment,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // モデルダウンロード進捗を通知する(requirements.md FR-2)。
  void OnDownloadProgress(
    const DownloadProgress& progress,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // ストリームがエラーで終了したことを通知する(requirements.md FR-6)。
  //
  // `message` はプラットフォーム固有の詳細情報(存在する場合)であり、
  // `code` が `TranscribeErrorCode.platformError` の場合に主として使う
  // 想定である。
  void OnStreamError(
    const TranscribeErrorCode& code,
    const std::string* message,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // ストリームが正常に終了したことを通知する。
  void OnStreamDone(
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace offline_stt_windows
#endif  // PIGEON_PIGEON_G_H_
