// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PigeonPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// モデルの状態を表す4値(design.md §2.2、requirements.md FR-1)。
///
/// `offline_stt` の `ModelState`(
/// `packages/offline_stt/lib/src/model_state.dart`)と値・順序を一致させる
/// こと。マッピングは各プラットフォーム実装側(`lib/src/android/` /
/// `lib/src/darwin/` の `model_state_mapping.dart`)で行う。
enum ModelState: Int, CaseIterable {
  case available = 0
  case downloadable = 1
  case downloading = 2
  case unavailable = 3
}

/// 共通エラー型(requirements.md FR-6、design.md §2.2 の `TranscribeException`
/// sealed階層に対応する列挙型)。
///
/// design.md §2.2 の `TranscribeException` 階層はDartのsealed classとして
/// 定義されているが、Pigeonはsealed classをコード生成対象にできない
/// (Kotlin/Swift/C++いずれの生成器も `_errorOnSealedClass` により拒否する)。
/// そのため、プラットフォーム境界を越えて型安全にエラー種別を伝える用途に
/// 限り、対応する列挙型としてこの `TranscribeErrorCode` を追加定義する
/// (design.mdには存在しない型だが、CodeRabbitの計画で明示的に追加が指示
/// されている)。ネイティブ側はこの列挙値を用いてエラーを通知し、Dart側
/// (各実装パッケージの `lib/`)がこれを `TranscribeException` の具象サブ
/// クラスへマッピングする。マッピング自体はPigeon生成コードの範囲外であり
/// 各実装パッケージ側の責務とする。
///
/// `PlatformException_`(design.mdの命名)には `code` / `message` の
/// 自由形式フィールドがあるため、`platformError` 1値に対応させる。
enum TranscribeErrorCode: Int, CaseIterable {
  case modelUnavailable = 0
  case localeUnsupported = 1
  case decodeFailed = 2
  case deviceUnsupported = 3
  case cancelled = 4
  case platformError = 5
}

/// モデルダウンロードの進捗(design.md §2.2)。
///
/// Generated class from Pigeon that represents data sent in messages.
struct DownloadProgress: Hashable, CustomStringConvertible {
  /// 進捗率(0.0〜1.0)。`null` は不定進捗を表す。
  var fraction: Double? = nil
  /// ダウンロードが完了したかどうか。
  var completed: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadProgress? {
    let fraction: Double? = nilOrValue(pigeonVar_list[0])
    let completed = pigeonVar_list[1] as! Bool

    return DownloadProgress(
      fraction: fraction,
      completed: completed
    )
  }
  func toList() -> [Any?] {
    return [
      fraction,
      completed,
    ]
  }
  static func == (lhs: DownloadProgress, rhs: DownloadProgress) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.fraction, rhs.fraction) && PigeonPigeonInternal.deepEquals(lhs.completed, rhs.completed)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadProgress")
    PigeonPigeonInternal.deepHash(value: fraction, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: completed, hasher: &hasher)
  }

  public var description: String {
    return "DownloadProgress(fraction: \(String(describing: fraction)), completed: \(String(describing: completed)))"
  }
}

/// `transcribeFile` へ渡すリクエスト(design.md §2.2)。
///
/// 注記: 現行の design.md §2.2 に `playbackRate` フィールドは存在しない
/// (2026-09-20 時点。PR #74 で追加予定だが本ブランチは分岐前のため未反映)。
/// そのため本スキーマでも `path` / `locale` の2フィールドのみを定義する。
///
/// Generated class from Pigeon that represents data sent in messages.
struct TranscribeRequest: Hashable, CustomStringConvertible {
  /// 文字起こし対象の音声ファイルパス。
  var path: String
  /// BCP-47形式のロケール(例: `ja-JP`)。
  var locale: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TranscribeRequest? {
    let path = pigeonVar_list[0] as! String
    let locale = pigeonVar_list[1] as! String

    return TranscribeRequest(
      path: path,
      locale: locale
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      locale,
    ]
  }
  static func == (lhs: TranscribeRequest, rhs: TranscribeRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.path, rhs.path) && PigeonPigeonInternal.deepEquals(lhs.locale, rhs.locale)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TranscribeRequest")
    PigeonPigeonInternal.deepHash(value: path, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: locale, hasher: &hasher)
  }

  public var description: String {
    return "TranscribeRequest(path: \(String(describing: path)), locale: \(String(describing: locale)))"
  }
}

/// 文字起こし結果の1セグメント(design.md §2.2)。
///
/// Generated class from Pigeon that represents data sent in messages.
struct TranscriptSegment: Hashable, CustomStringConvertible {
  /// 認識されたテキスト。
  var text: String
  /// 確定結果かどうか(`false` はpartial)。
  var isFinal: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TranscriptSegment? {
    let text = pigeonVar_list[0] as! String
    let isFinal = pigeonVar_list[1] as! Bool

    return TranscriptSegment(
      text: text,
      isFinal: isFinal
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isFinal,
    ]
  }
  static func == (lhs: TranscriptSegment, rhs: TranscriptSegment) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PigeonPigeonInternal.deepEquals(lhs.text, rhs.text) && PigeonPigeonInternal.deepEquals(lhs.isFinal, rhs.isFinal)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TranscriptSegment")
    PigeonPigeonInternal.deepHash(value: text, hasher: &hasher)
    PigeonPigeonInternal.deepHash(value: isFinal, hasher: &hasher)
  }

  public var description: String {
    return "TranscriptSegment(text: \(String(describing: text)), isFinal: \(String(describing: isFinal)))"
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModelState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TranscribeErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return DownloadProgress.fromList(self.readValue() as! [Any?])
    case 132:
      return TranscribeRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return TranscriptSegment.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ModelState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? TranscribeErrorCode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? DownloadProgress {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TranscribeRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? TranscriptSegment {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}

var pigeonPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: PigeonPigeonCodecReaderWriter());


/// Method チャネル(design.md §2.3)。
///
/// `downloadModel` / `transcribeFile` は開始のみを担う。進捗・結果は
/// 下記 `OfflineSttStreamEvents`(EventChannel)で配信する
/// (design.md §2.3、requirements.md FR-2 FR-3)。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OfflineSttHostApi {
  /// 対象ロケールのモデル状態を確認する(requirements.md FR-1)。
  ///
  /// ## `@async` を付与する理由
  /// Darwin実装は `AssetInventory.status(forModules:)` /
  /// `SpeechTranscriber.supportedLocale(equivalentTo:)` という
  /// Swift ConcurrencyのasyncAPIを呼ばなければ戻り値の `ModelState` を
  /// 確定できない(`ModelAvailability.swift` 参照)。`@async` を付けない
  /// 場合、Pigeonが生成するSwiftプロトコルは同期シグネチャ
  /// (`throws -> ModelState`)になり、非同期APIの結果を得るには
  /// `DispatchSemaphore` 等でFlutterのプラットフォームスレッドを
  /// ブロックする回避策が必要になってしまう(ANR・デッドロックの危険が
  /// あり不可)。`@async` を付けることでPigeonは `completion:` クロージャ
  /// 形式の非同期シグネチャを生成し、スレッドをブロックせずに
  /// `async`/`await` へ素直に橋渡しできる。
  func checkModel(locale: String, completion: @escaping (Result<ModelState, Error>) -> Void)
  /// モデルダウンロードを開始する(requirements.md FR-2)。
  ///
  /// 進捗は `OfflineSttStreamEvents.downloadProgress()` のEventChannelで
  /// 配信される。本メソッド自体は開始要求のみを表し、値を返さない。
  ///
  /// ## `@async` を付けない理由
  /// このメソッドは「開始要求のみ」を表す契約であり、実装は非同期APIの
  /// 完了を待たずに `Task` を起動して直ちに制御を返せる(Swift実装では
  /// `Task.cancel()` と新規 `Task { ... }` の生成のみを行い、いずれも
  /// 同期処理である。`OfflineSttApiImpl.downloadModel` 参照)。非同期APIの
  /// 実行結果自体は `downloadProgress` のEventChannelで別途配信されるため、
  /// 本メソッドの戻り値(`void`)を得るために非同期処理の完了を待つ必要が
  /// ない。
  func downloadModel(locale: String) throws
  /// 音声ファイルの文字起こしを開始する(requirements.md FR-3)。
  ///
  /// 結果は `OfflineSttStreamEvents.segments()` のEventChannelで配信される。
  /// 本メソッド自体は開始要求のみを表し、値を返さない。
  ///
  /// design.md §3 のとおり、`checkModel()` が `ModelState.available` 以外
  /// を返す状態でこのメソッドが呼ばれた場合、ネイティブ側は即座にエラーを
  /// 返さなければならない(内部で暗黙的にダウンロードを開始してはならない)。
  ///
  /// ## `@async` を付けない理由
  /// `downloadModel` と同様に「開始要求のみ」の契約であり、`Task` を
  /// 起動して直ちに制御を返せる同期的な実装で足りる
  /// (`OfflineSttApiImpl.transcribeFile` 参照)。
  func transcribeFile(request: TranscribeRequest) throws
  /// 実行中のダウンロード、または文字起こしセッションをキャンセルする
  /// (requirements.md FR-3)。
  ///
  /// design.md §3 のとおり同時セッションはv1では1本に制限されるため、
  /// キャンセル対象を明示するパラメータは持たない(実行中の1本のみが
  /// 対象になる)。
  ///
  /// ## `@async` を付けない理由
  /// `Task.cancel()` の呼び出しのみを行う完全に同期的な処理であり、
  /// 非同期APIを一切呼ばない(`OfflineSttApiImpl.cancel` 参照)。
  func cancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OfflineSttHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `OfflineSttHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OfflineSttHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 対象ロケールのモデル状態を確認する(requirements.md FR-1)。
    ///
    /// ## `@async` を付与する理由
    /// Darwin実装は `AssetInventory.status(forModules:)` /
    /// `SpeechTranscriber.supportedLocale(equivalentTo:)` という
    /// Swift ConcurrencyのasyncAPIを呼ばなければ戻り値の `ModelState` を
    /// 確定できない(`ModelAvailability.swift` 参照)。`@async` を付けない
    /// 場合、Pigeonが生成するSwiftプロトコルは同期シグネチャ
    /// (`throws -> ModelState`)になり、非同期APIの結果を得るには
    /// `DispatchSemaphore` 等でFlutterのプラットフォームスレッドを
    /// ブロックする回避策が必要になってしまう(ANR・デッドロックの危険が
    /// あり不可)。`@async` を付けることでPigeonは `completion:` クロージャ
    /// 形式の非同期シグネチャを生成し、スレッドをブロックせずに
    /// `async`/`await` へ素直に橋渡しできる。
    let checkModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.checkModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeArg = args[0] as! String
        api.checkModel(locale: localeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkModelChannel.setMessageHandler(nil)
    }
    /// モデルダウンロードを開始する(requirements.md FR-2)。
    ///
    /// 進捗は `OfflineSttStreamEvents.downloadProgress()` のEventChannelで
    /// 配信される。本メソッド自体は開始要求のみを表し、値を返さない。
    ///
    /// ## `@async` を付けない理由
    /// このメソッドは「開始要求のみ」を表す契約であり、実装は非同期APIの
    /// 完了を待たずに `Task` を起動して直ちに制御を返せる(Swift実装では
    /// `Task.cancel()` と新規 `Task { ... }` の生成のみを行い、いずれも
    /// 同期処理である。`OfflineSttApiImpl.downloadModel` 参照)。非同期APIの
    /// 実行結果自体は `downloadProgress` のEventChannelで別途配信されるため、
    /// 本メソッドの戻り値(`void`)を得るために非同期処理の完了を待つ必要が
    /// ない。
    let downloadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.downloadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeArg = args[0] as! String
        do {
          try api.downloadModel(locale: localeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      downloadModelChannel.setMessageHandler(nil)
    }
    /// 音声ファイルの文字起こしを開始する(requirements.md FR-3)。
    ///
    /// 結果は `OfflineSttStreamEvents.segments()` のEventChannelで配信される。
    /// 本メソッド自体は開始要求のみを表し、値を返さない。
    ///
    /// design.md §3 のとおり、`checkModel()` が `ModelState.available` 以外
    /// を返す状態でこのメソッドが呼ばれた場合、ネイティブ側は即座にエラーを
    /// 返さなければならない(内部で暗黙的にダウンロードを開始してはならない)。
    ///
    /// ## `@async` を付けない理由
    /// `downloadModel` と同様に「開始要求のみ」の契約であり、`Task` を
    /// 起動して直ちに制御を返せる同期的な実装で足りる
    /// (`OfflineSttApiImpl.transcribeFile` 参照)。
    let transcribeFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.transcribeFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transcribeFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TranscribeRequest
        do {
          try api.transcribeFile(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      transcribeFileChannel.setMessageHandler(nil)
    }
    /// 実行中のダウンロード、または文字起こしセッションをキャンセルする
    /// (requirements.md FR-3)。
    ///
    /// design.md §3 のとおり同時セッションはv1では1本に制限されるため、
    /// キャンセル対象を明示するパラメータは持たない(実行中の1本のみが
    /// 対象になる)。
    ///
    /// ## `@async` を付けない理由
    /// `Task.cancel()` の呼び出しのみを行う完全に同期的な処理であり、
    /// 非同期APIを一切呼ばない(`OfflineSttApiImpl.cancel` 参照)。
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// EventChannel(design.md §2.3)。Android(Kotlin) / Darwin(Swift) 向け。
class SegmentsStreamHandler: PigeonEventChannelWrapper<TranscriptSegment> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: SegmentsStreamHandler) {
    var channelName = "dev.flutter.pigeon.offline_stt.OfflineSttStreamEvents.segments"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<TranscriptSegment>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pigeonPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class DownloadProgressStreamHandler: PigeonEventChannelWrapper<DownloadProgress> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: DownloadProgressStreamHandler) {
    var channelName = "dev.flutter.pigeon.offline_stt.OfflineSttStreamEvents.downloadProgress"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<DownloadProgress>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pigeonPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
