// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// モデルの状態を表す4値(design.md §2.2、requirements.md FR-1)。
///
/// `offline_stt_platform_interface` の `ModelState`(
/// `packages/offline_stt_platform_interface/lib/src/model_state.dart`)と
/// 値・順序を一致させること。マッピングは各実装パッケージ側で行う。
enum ModelState {
  available,
  downloadable,
  downloading,
  unavailable,
}

/// 共通エラー型(requirements.md FR-6、design.md §2.2 の `TranscribeException`
/// sealed階層に対応する列挙型)。
///
/// design.md §2.2 の `TranscribeException` 階層はDartのsealed classとして
/// 定義されているが、Pigeonはsealed classをコード生成対象にできない
/// (Kotlin/Swift/C++いずれの生成器も `_errorOnSealedClass` により拒否する)。
/// そのため、プラットフォーム境界を越えて型安全にエラー種別を伝える用途に
/// 限り、対応する列挙型としてこの `TranscribeErrorCode` を追加定義する
/// (design.mdには存在しない型だが、CodeRabbitの計画で明示的に追加が指示
/// されている)。ネイティブ側はこの列挙値を用いてエラーを通知し、Dart側
/// (各実装パッケージの `lib/`)がこれを `TranscribeException` の具象サブ
/// クラスへマッピングする。マッピング自体はPigeon生成コードの範囲外であり
/// 各実装パッケージ側の責務とする。
///
/// `PlatformException_`(design.mdの命名)には `code` / `message` の
/// 自由形式フィールドがあるため、`platformError` 1値に対応させる。
enum TranscribeErrorCode {
  modelUnavailable,
  localeUnsupported,
  decodeFailed,
  deviceUnsupported,
  cancelled,
  platformError,
}

/// モデルダウンロードの進捗(design.md §2.2)。
class DownloadProgress {
  DownloadProgress({
    this.fraction,
    required this.completed,
  });

  /// 進捗率(0.0〜1.0)。`null` は不定進捗を表す。
  double? fraction;

  /// ダウンロードが完了したかどうか。
  bool completed;

  List<Object?> _toList() {
    return <Object?>[
      fraction,
      completed,
    ];
  }

  Object encode() {
    return _toList();  }

  static DownloadProgress decode(Object result) {
    result as List<Object?>;
    return DownloadProgress(
      fraction: result[0] as double?,
      completed: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fraction, other.fraction) && _deepEquals(completed, other.completed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DownloadProgress(fraction: $fraction, completed: $completed)';
  }
}

/// `transcribeFile` へ渡すリクエスト(design.md §2.2)。
///
/// 注記: 現行の design.md §2.2 に `playbackRate` フィールドは存在しない
/// (2026-09-20 時点。PR #74 で追加予定だが本ブランチは分岐前のため未反映)。
/// そのため本スキーマでも `path` / `locale` の2フィールドのみを定義する。
class TranscribeRequest {
  TranscribeRequest({
    required this.path,
    required this.locale,
  });

  /// 文字起こし対象の音声ファイルパス。
  String path;

  /// BCP-47形式のロケール(例: `ja-JP`)。
  String locale;

  List<Object?> _toList() {
    return <Object?>[
      path,
      locale,
    ];
  }

  Object encode() {
    return _toList();  }

  static TranscribeRequest decode(Object result) {
    result as List<Object?>;
    return TranscribeRequest(
      path: result[0]! as String,
      locale: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TranscribeRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(locale, other.locale);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TranscribeRequest(path: $path, locale: $locale)';
  }
}

/// 文字起こし結果の1セグメント(design.md §2.2)。
class TranscriptSegment {
  TranscriptSegment({
    required this.text,
    required this.isFinal,
  });

  /// 認識されたテキスト。
  String text;

  /// 確定結果かどうか(`false` はpartial)。
  bool isFinal;

  List<Object?> _toList() {
    return <Object?>[
      text,
      isFinal,
    ];
  }

  Object encode() {
    return _toList();  }

  static TranscriptSegment decode(Object result) {
    result as List<Object?>;
    return TranscriptSegment(
      text: result[0]! as String,
      isFinal: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TranscriptSegment || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) && _deepEquals(isFinal, other.isFinal);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TranscriptSegment(text: $text, isFinal: $isFinal)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ModelState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is TranscribeErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DownloadProgress) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TranscribeRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is TranscriptSegment) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ModelState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : TranscribeErrorCode.values[value];
      case 131:
        return DownloadProgress.decode(readValue(buffer)!);
      case 132:
        return TranscribeRequest.decode(readValue(buffer)!);
      case 133:
        return TranscriptSegment.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Method チャネル(design.md §2.3)。
///
/// `downloadModel` / `transcribeFile` は開始のみを担う。進捗・結果は
/// 下記 `OfflineSttStreamEvents`(EventChannel)で配信する
/// (design.md §2.3、requirements.md FR-2 FR-3)。
class OfflineSttHostApi {
  /// Constructor for [OfflineSttHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OfflineSttHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 対象ロケールのモデル状態を確認する(requirements.md FR-1)。
  ///
  /// ## `@async` を付与する理由
  /// Darwin実装は `AssetInventory.status(forModules:)` /
  /// `SpeechTranscriber.supportedLocale(equivalentTo:)` という
  /// Swift ConcurrencyのasyncAPIを呼ばなければ戻り値の `ModelState` を
  /// 確定できない(`ModelAvailability.swift` 参照)。`@async` を付けない
  /// 場合、Pigeonが生成するSwiftプロトコルは同期シグネチャ
  /// (`throws -> ModelState`)になり、非同期APIの結果を得るには
  /// `DispatchSemaphore` 等でFlutterのプラットフォームスレッドを
  /// ブロックする回避策が必要になってしまう(ANR・デッドロックの危険が
  /// あり不可)。`@async` を付けることでPigeonは `completion:` クロージャ
  /// 形式の非同期シグネチャを生成し、スレッドをブロックせずに
  /// `async`/`await` へ素直に橋渡しできる。
  Future<ModelState> checkModel(String locale) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_android.OfflineSttHostApi.checkModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ModelState;
  }

  /// モデルダウンロードを開始する(requirements.md FR-2)。
  ///
  /// 進捗は `OfflineSttStreamEvents.downloadProgress()` のEventChannelで
  /// 配信される。本メソッド自体は開始要求のみを表し、値を返さない。
  ///
  /// ## `@async` を付けない理由
  /// このメソッドは「開始要求のみ」を表す契約であり、実装は非同期APIの
  /// 完了を待たずに `Task` を起動して直ちに制御を返せる(Swift実装では
  /// `Task.cancel()` と新規 `Task { ... }` の生成のみを行い、いずれも
  /// 同期処理である。`OfflineSttApiImpl.downloadModel` 参照)。非同期APIの
  /// 実行結果自体は `downloadProgress` のEventChannelで別途配信されるため、
  /// 本メソッドの戻り値(`void`)を得るために非同期処理の完了を待つ必要が
  /// ない。
  Future<void> downloadModel(String locale) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_android.OfflineSttHostApi.downloadModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 音声ファイルの文字起こしを開始する(requirements.md FR-3)。
  ///
  /// 結果は `OfflineSttStreamEvents.segments()` のEventChannelで配信される。
  /// 本メソッド自体は開始要求のみを表し、値を返さない。
  ///
  /// design.md §3 のとおり、`checkModel()` が `ModelState.available` 以外
  /// を返す状態でこのメソッドが呼ばれた場合、ネイティブ側は即座にエラーを
  /// 返さなければならない(内部で暗黙的にダウンロードを開始してはならない)。
  ///
  /// ## `@async` を付けない理由
  /// `downloadModel` と同様に「開始要求のみ」の契約であり、`Task` を
  /// 起動して直ちに制御を返せる同期的な実装で足りる
  /// (`OfflineSttApiImpl.transcribeFile` 参照)。
  Future<void> transcribeFile(TranscribeRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_android.OfflineSttHostApi.transcribeFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 実行中のダウンロード、または文字起こしセッションをキャンセルする
  /// (requirements.md FR-3)。
  ///
  /// design.md §3 のとおり同時セッションはv1では1本に制限されるため、
  /// キャンセル対象を明示するパラメータは持たない(実行中の1本のみが
  /// 対象になる)。
  ///
  /// ## `@async` を付けない理由
  /// `Task.cancel()` の呼び出しのみを行う完全に同期的な処理であり、
  /// 非同期APIを一切呼ばない(`OfflineSttApiImpl.cancel` 参照)。
  Future<void> cancel() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.offline_stt_android.OfflineSttHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// EventChannel(design.md §2.3)。Android(Kotlin) / Darwin(Swift) 向け。
///
/// Pigeonの `@EventChannelApi` はDart / Kotlin / Swift の生成器のみに
/// 対応しており、C++には対応していない(本ファイル冒頭のコメント、および
/// 実際に `--cpp_header_out` 等を指定してPigeonを実行した結果で確認済み)。
/// 文字起こし結果のストリーム(requirements.md FR-3)。
///
/// Returns a broadcast [Stream] of events from the `segments` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<TranscriptSegment> segments( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel segmentsChannel =
      EventChannel('dev.flutter.pigeon.offline_stt_android.OfflineSttStreamEvents.segments$instanceName', pigeonMethodCodec);
  return segmentsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as TranscriptSegment;
  });
}
    
/// モデルダウンロード進捗のストリーム(requirements.md FR-2)。
///
/// Returns a broadcast [Stream] of events from the `downloadProgress` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<DownloadProgress> downloadProgress( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel downloadProgressChannel =
      EventChannel('dev.flutter.pigeon.offline_stt_android.OfflineSttStreamEvents.downloadProgress$instanceName', pigeonMethodCodec);
  return downloadProgressChannel.receiveBroadcastStream().map((dynamic event) {
    return event as DownloadProgress;
  });
}
    
