// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.moongift.offline_stt

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * モデルの状態を表す4値(design.md §2.2、requirements.md FR-1)。
 *
 * `offline_stt` の `ModelState`(
 * `packages/offline_stt/lib/src/model_state.dart`)と値・順序を一致させる
 * こと。マッピングは各プラットフォーム実装側(`lib/src/android/` /
 * `lib/src/darwin/` の `model_state_mapping.dart`)で行う。
 */
enum class ModelState(val raw: Int) {
  AVAILABLE(0),
  DOWNLOADABLE(1),
  DOWNLOADING(2),
  UNAVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): ModelState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 共通エラー型(requirements.md FR-6、design.md §2.2 の `TranscribeException`
 * sealed階層に対応する列挙型)。
 *
 * design.md §2.2 の `TranscribeException` 階層はDartのsealed classとして
 * 定義されているが、Pigeonはsealed classをコード生成対象にできない
 * (Kotlin/Swift/C++いずれの生成器も `_errorOnSealedClass` により拒否する)。
 * そのため、プラットフォーム境界を越えて型安全にエラー種別を伝える用途に
 * 限り、対応する列挙型としてこの `TranscribeErrorCode` を追加定義する
 * (design.mdには存在しない型だが、CodeRabbitの計画で明示的に追加が指示
 * されている)。ネイティブ側はこの列挙値を用いてエラーを通知し、Dart側
 * (各実装パッケージの `lib/`)がこれを `TranscribeException` の具象サブ
 * クラスへマッピングする。マッピング自体はPigeon生成コードの範囲外であり
 * 各実装パッケージ側の責務とする。
 *
 * `PlatformException_`(design.mdの命名)には `code` / `message` の
 * 自由形式フィールドがあるため、`platformError` 1値に対応させる。
 */
enum class TranscribeErrorCode(val raw: Int) {
  MODEL_UNAVAILABLE(0),
  LOCALE_UNSUPPORTED(1),
  DECODE_FAILED(2),
  DEVICE_UNSUPPORTED(3),
  CANCELLED(4),
  PLATFORM_ERROR(5);

  companion object {
    fun ofRaw(raw: Int): TranscribeErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * モデルダウンロードの進捗(design.md §2.2)。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DownloadProgress (
  /** 進捗率(0.0〜1.0)。`null` は不定進捗を表す。 */
  val fraction: Double? = null,
  /** ダウンロードが完了したかどうか。 */
  val completed: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadProgress {
      val fraction = pigeonVar_list[0] as Double?
      val completed = pigeonVar_list[1] as Boolean
      return DownloadProgress(fraction, completed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fraction,
      completed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadProgress
    return PigeonPigeonUtils.deepEquals(this.fraction, other.fraction) && PigeonPigeonUtils.deepEquals(this.completed, other.completed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.fraction)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.completed)
    return result
  }
  override fun toString(): String {
    return "DownloadProgress(fraction=$fraction, completed=$completed)"
  }
}

/**
 * `transcribeFile` へ渡すリクエスト(design.md §2.2)。
 *
 * 注記: 現行の design.md §2.2 に `playbackRate` フィールドは存在しない
 * (2026-09-20 時点。PR #74 で追加予定だが本ブランチは分岐前のため未反映)。
 * そのため本スキーマでも `path` / `locale` の2フィールドのみを定義する。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TranscribeRequest (
  /** 文字起こし対象の音声ファイルパス。 */
  val path: String,
  /** BCP-47形式のロケール(例: `ja-JP`)。 */
  val locale: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TranscribeRequest {
      val path = pigeonVar_list[0] as String
      val locale = pigeonVar_list[1] as String
      return TranscribeRequest(path, locale)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      locale,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TranscribeRequest
    return PigeonPigeonUtils.deepEquals(this.path, other.path) && PigeonPigeonUtils.deepEquals(this.locale, other.locale)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.path)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.locale)
    return result
  }
  override fun toString(): String {
    return "TranscribeRequest(path=$path, locale=$locale)"
  }
}

/**
 * 文字起こし結果の1セグメント(design.md §2.2)。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TranscriptSegment (
  /** 認識されたテキスト。 */
  val text: String,
  /** 確定結果かどうか(`false` はpartial)。 */
  val isFinal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TranscriptSegment {
      val text = pigeonVar_list[0] as String
      val isFinal = pigeonVar_list[1] as Boolean
      return TranscriptSegment(text, isFinal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      isFinal,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TranscriptSegment
    return PigeonPigeonUtils.deepEquals(this.text, other.text) && PigeonPigeonUtils.deepEquals(this.isFinal, other.isFinal)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonPigeonUtils.deepHash(this.text)
    result = 31 * result + PigeonPigeonUtils.deepHash(this.isFinal)
    return result
  }
  override fun toString(): String {
    return "TranscriptSegment(text=$text, isFinal=$isFinal)"
  }
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ModelState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TranscribeErrorCode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadProgress.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TranscribeRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TranscriptSegment.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ModelState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is TranscribeErrorCode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is DownloadProgress -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is TranscribeRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TranscriptSegment -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val PigeonPigeonMethodCodec = StandardMethodCodec(PigeonPigeonCodec())


/**
 * Method チャネル(design.md §2.3)。
 *
 * `downloadModel` / `transcribeFile` は開始のみを担う。進捗・結果は
 * 下記 `OfflineSttStreamEvents`(EventChannel)で配信する
 * (design.md §2.3、requirements.md FR-2 FR-3)。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface OfflineSttHostApi {
  /**
   * 対象ロケールのモデル状態を確認する(requirements.md FR-1)。
   *
   * ## `@async` を付与する理由
   * Darwin実装は `AssetInventory.status(forModules:)` /
   * `SpeechTranscriber.supportedLocale(equivalentTo:)` という
   * Swift ConcurrencyのasyncAPIを呼ばなければ戻り値の `ModelState` を
   * 確定できない(`ModelAvailability.swift` 参照)。`@async` を付けない
   * 場合、Pigeonが生成するSwiftプロトコルは同期シグネチャ
   * (`throws -> ModelState`)になり、非同期APIの結果を得るには
   * `DispatchSemaphore` 等でFlutterのプラットフォームスレッドを
   * ブロックする回避策が必要になってしまう(ANR・デッドロックの危険が
   * あり不可)。`@async` を付けることでPigeonは `completion:` クロージャ
   * 形式の非同期シグネチャを生成し、スレッドをブロックせずに
   * `async`/`await` へ素直に橋渡しできる。
   */
  fun checkModel(locale: String, callback: (Result<ModelState>) -> Unit)
  /**
   * このプラットフォームが扱えるロケールの一覧を返す(requirements.md FR-5)。
   *
   * 返すのは**BCP-47文字列の集合**であり、`ModelState.available` な
   * ロケールの一覧ではない。未ダウンロードのロケールも含む。
   *
   * 列挙できない場合(Android API 33未満、Darwin OS 26未満・
   * `SpeechTranscriber.isAvailable == false` 等)は空リストを返さず、
   * `deviceUnsupported` のエラーを返さなければならない。空リストは
   * 「対応ロケールが1つも無い」と「そもそも列挙できない」を区別できず、
   * 呼び出し側を誤らせるためである(フォールバック禁止)。
   *
   * ## `@async` を付与する理由
   * [checkModel] と同じ事情である。Darwin実装は
   * `SpeechTranscriber.supportedLocales`(`static var ... { get async }`)
   * という Swift Concurrency の async プロパティを読まなければ結果を確定
   * できない(`ModelAvailability.swift` 参照)。`@async` を付けない場合、
   * Pigeonが生成するSwiftプロトコルは同期シグネチャになり、非同期APIの
   * 結果を得るには `DispatchSemaphore` 等でFlutterのプラットフォーム
   * スレッドをブロックする回避策が必要になってしまう(ANR・デッドロックの
   * 危険があり不可)。Android実装も `checkRecognitionSupport()` の
   * コールバック待ちを伴うため同様である。
   */
  fun supportedLocales(callback: (Result<List<String>>) -> Unit)
  /**
   * モデルダウンロードを開始する(requirements.md FR-2)。
   *
   * 進捗は `OfflineSttStreamEvents.downloadProgress()` のEventChannelで
   * 配信される。本メソッド自体は開始要求のみを表し、値を返さない。
   *
   * ## `@async` を付けない理由
   * このメソッドは「開始要求のみ」を表す契約であり、実装は非同期APIの
   * 完了を待たずに `Task` を起動して直ちに制御を返せる(Swift実装では
   * `Task.cancel()` と新規 `Task { ... }` の生成のみを行い、いずれも
   * 同期処理である。`OfflineSttApiImpl.downloadModel` 参照)。非同期APIの
   * 実行結果自体は `downloadProgress` のEventChannelで別途配信されるため、
   * 本メソッドの戻り値(`void`)を得るために非同期処理の完了を待つ必要が
   * ない。
   */
  fun downloadModel(locale: String)
  /**
   * 音声ファイルの文字起こしを開始する(requirements.md FR-3)。
   *
   * 結果は `OfflineSttStreamEvents.segments()` のEventChannelで配信される。
   * 本メソッド自体は開始要求のみを表し、値を返さない。
   *
   * design.md §3 のとおり、`checkModel()` が `ModelState.available` 以外
   * を返す状態でこのメソッドが呼ばれた場合、ネイティブ側は即座にエラーを
   * 返さなければならない(内部で暗黙的にダウンロードを開始してはならない)。
   *
   * ## `@async` を付けない理由
   * `downloadModel` と同様に「開始要求のみ」の契約であり、`Task` を
   * 起動して直ちに制御を返せる同期的な実装で足りる
   * (`OfflineSttApiImpl.transcribeFile` 参照)。
   */
  fun transcribeFile(request: TranscribeRequest)
  /**
   * 実行中のダウンロード、または文字起こしセッションをキャンセルする
   * (requirements.md FR-3)。
   *
   * design.md §3 のとおり同時セッションはv1では1本に制限されるため、
   * キャンセル対象を明示するパラメータは持たない(実行中の1本のみが
   * 対象になる)。
   *
   * ## `@async` を付けない理由
   * `Task.cancel()` の呼び出しのみを行う完全に同期的な処理であり、
   * 非同期APIを一切呼ばない(`OfflineSttApiImpl.cancel` 参照)。
   */
  fun cancel()

  companion object {
    /** The codec used by OfflineSttHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `OfflineSttHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OfflineSttHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.checkModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val localeArg = args[0] as String
            api.checkModel(localeArg) { result: Result<ModelState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.supportedLocales$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.supportedLocales{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.downloadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val localeArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.downloadModel(localeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.transcribeFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as TranscribeRequest
            val wrapped: List<Any?> = try {
              api.transcribeFile(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.offline_stt.OfflineSttHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancel()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PigeonPigeonStreamHandler<T>(
    val wrapper: PigeonPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PigeonPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** EventChannel(design.md §2.3)。Android(Kotlin) / Darwin(Swift) 向け。 */
abstract class SegmentsStreamHandler : PigeonPigeonEventChannelWrapper<TranscriptSegment> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: SegmentsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.offline_stt.OfflineSttStreamEvents.segments"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonPigeonStreamHandler<TranscriptSegment>(streamHandler)
      EventChannel(messenger, channelName, PigeonPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PigeonPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<TranscriptSegment>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class DownloadProgressStreamHandler : PigeonPigeonEventChannelWrapper<DownloadProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: DownloadProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.offline_stt.OfflineSttStreamEvents.downloadProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonPigeonStreamHandler<DownloadProgress>(streamHandler)
      EventChannel(messenger, channelName, PigeonPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PigeonPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<DownloadProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
